var editor=document.getElementById("editor"),editorButton=document.getElementById("editor-button"),editorHiddenInput=document.getElementById("editor-hidden-input"),editorFilenameInput=document.getElementById("editor-filename"),editorCtrl={resetCaretPosition:function(a){if(document.createRange){var b=document.getSelection();console.log("ended up selecting",b,a);this.getCurrentLine(b);rng=document.createRange();rng.selectNodeContents(a);rng.collapse(!1);b=window.getSelection();b.removeAllRanges();b.addRange(rng)}},
getCurrentLine:function(a,b,c){a=a?a:document.getSelection();var d=c?a:a.anchorNode;c=c?c:a;b=b?b:0;if(!d.parentNode.previousSibling&&"#text"===d.nodeName||"editor"===d.parentNode.id&&!d.previousSibling)return c.anchorNode.textContent.lastIndexOf(" "),a=(a=c.anchorNode.textContent.match(/[\/\s(](?!.*[\/\s(])/))?a.index+1:-1,{index:b,lastWord:c.anchorNode.textContent.substring(a,c.anchorOffset),lastSpacerOffset:a,sourceElement:c};if("DIV"===d.nodeName&&d.previousSibling)return this.getCurrentLine(d.previousSibling,
b+1,c);if("#text"===d.nodeName&&"editor"!==d.parentNode.id)return this.getCurrentLine(d.parentNode.previousSibling,b+1,c)},replaceReservedWords:function(){var a=this.getCurrentLine(),a=editor.childNodes[a.index],b=a.innerHTML.match(/(\bif\b|\belse\b|\bvar\b|[~=])(?!(<\/span>|"))/gi);if(b){console.log(b);var c=document.createElement("span"),d=document.createTextNode(""),f=document.getSelection();c.contentEditable="false";for(var e=b.length-1;0<=e;e--){switch(b[e]){case "~":c.className="coordinate";
break;case "=":case "if":case "else":c.className="control-flow-statement";break;case "var":c.className="variable"}findAndReplaceDOMText(a,{find:b[e],wrap:c});f.anchorNode.nextSibling?null:f.anchorNode.insertBefore(d,f.anchorNode.nextSibling)}editorCtrl.resetCaretPosition(a)}},fixEmptyParent:function(){if("<br>"===editor.innerHTML||""===editor.innerHTML){console.log("now");var a=document.createElement("div"),b=document.createElement("br");a.appendChild(b);"<br>"===editor.innerHTML?editor.replaceChild(a,
editor.firstChild):editor.appendChild(a)}},getTextContent:function(){for(var a="",b=0;b<editor.childNodes.length;b++)a+=editor.childNodes[b].textContent+"\n";console.log("str is",a);return a},setTextContent:function(){editorHiddenInput.value=editorCtrl.getTextContent()},sendTextContent:function(a){var b=new XMLHttpRequest;console.log("textContent is",a);b.onreadystatechange=function(){4===b.readyState&&console.log("we have something",b.responseText)};b.open("POST","schematic",!0);b.setRequestHeader("Content-Type",
"application/x-www-form-urlencoded; charset=UTF-8");b.send("source="+a)}},autocomplete={active:!1,matches:[],_lastIndex:0,_lastWord:"",_lastOffset:0,getMatchSet:function(a){var b="achievement ban ban-ip banlist blockdata clear clone debug defaultgamemode deop difficulty effect enchant entitydata execute fill gamemode gamerule give help kick kill list me op pardon particle playsound publish replaceitem save save-all save-off save-on say scoreboard seed setblock setidletimeout setworldspawn spawnpoint spreadplayers stats stop stopsound summon teleport tell tellraw testfor testforblock testforblocks time title toggledownfall tp trigger weather whitelist worldborder xp".split(" "),
c=[];a=a.replace("/","").replace("(","").replace("&nbsp;","");console.log("trying to match",a);for(var d=b.length-1;0<=d;d--)b[d].startsWith(a)&&c.push(b[d]);return c},reset:function(){this._lastWord="";this._lastIndex=this._lastOffset=0;this.active=!1;this.matches=[]},_replace:function(a,b,c){a=a.anchorNode;var d=this.matches[this._lastIndex];if(!d)this._lastIndex=0,d=this.matches[this._lastIndex];else if(c===d||0===this.matches.length)return;this._lastWord=d;this._lastIndex++;console.log("_replace here, working with",
c,"offset",b,"element",a);0<b&&(a.splitText(b),a=a.nextSibling);console.log("_replace here, working with next",d,"offset",b,"element",a);console.log("matches",this.matches);findAndReplaceDOMText(a,{find:c,replace:d});this._lastOffset=b+c.length},cycle:function(){var a=editorCtrl.getCurrentLine();this.active?(console.log("now going with",a.sourceElement),this._replace(a.sourceElement,-1,this._lastWord)):(this.matches=this.getMatchSet(a.lastWord),this.active=!0,this._replace(a.sourceElement,a.lastSpacerOffset,
a.lastWord))}};editor.onkeyup=function(a){a=String.fromCharCode(a.which);editorCtrl.fixEmptyParent();/[a-z\d]/i.test(a)&&(autocomplete.reset(),editorCtrl.replaceReservedWords())};editor.onkeydown=function(a){9===a.which&&(a.preventDefault(),autocomplete.cycle(editorCtrl.getCurrentLine()))};
